[workspace]

members = [
    "generic_instance_derive",
    "delegate_derive",
    "syn_generics",
    "syn_generics_derive",
    "serde_nom",
    "serde_nom_derive",
    "just_diff",
    "just_diff_derive",
    "lib_main",
]