unstable_features = true
edition = "2018"
# brace_style = "PreferSameLine"
format_strings = true
fn_single_line = true
merge_imports = true
max_width = 120
overflow_delimited_expr = true
wrap_comments = true