[package]
name = "serde_nom"
version = "0.1.0"
authors = ["liranxiao"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.1.2"
byte_string = "1.0"
byteorder = "1"
num = "0.3.0"
ordered-float = "2.0.0"